name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: npyrz
          outputs: |
            ./output/pacman-contribution-graph-dark.svg?palette=github-dark
            ./output/pacman-contribution-graph.svg

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
